version: "3.9"

services:
  db:
    image: postgres
    restart: always
    container_name: 'demo_application_db'
    volumes:
      - demo_application_db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 1s
      timeout: 5s
      retries: 20

volumes:
  demo_application_db_volume:
    driver: local